from .client import SingTownAIClient
from .mock import (
    MOCK_TRAIN_CLASSIFICATION,
    MOCK_TRAIN_OBJECT_DETECTION,
    MOCK_DEPLOY_CLASSIFICATION,
)

__all__ = [
    "SingTownAIClient",
    "MOCK_TRAIN_CLASSIFICATION",
    "MOCK_TRAIN_OBJECT_DETECTION",
    "MOCK_DEPLOY_CLASSIFICATION",
]
